### PR TITLE
fix: camelCase a separator should return an empty string

### LINKED ISSUE #98: Passed in a single seperator, return the original seperator
```js
camelCase('-');
//=> '-'
```

Is this a bug?

### PR DESCRIPTION
**Pull request by tychenjiajun**
fix #98

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -84,6 +84,10 @@ const camelCase = (input, options) => {
 		string => string.toLocaleUpperCase(options.locale);
 
 	if (input.length === 1) {
+		if (input.match(SEPARATORS)) {
```
Comment (sindresorhus) [inline index.js:87]: `RegExp#test` is the correct method to use here.

Comment (tychenjiajun) [reply index.js]: done
