### PR TITLE
Removing casing to characters after a number that are followed by a separator (issue #77)

### LINKED ISSUE #77: Converting either volume_3d or volume3d results in volume3D making it impossible to decamelize
How to reproduce:
```
console.log(camelcase('volume_3d')); // volume3D
console.log(camelcase('volume3d')); // volume3D
```

this operates under the assumption that decamelizing should return the string to its original decamelized version but I'm not sure how that would be possible for strings in this format.

### PR DESCRIPTION
**Pull request by JCrandall101**
### In this PR
Based on issue #77 for the following [comment](https://github.com/sindresorhus/camelcase/issues/77#issuecomment-1025489619)

The following example the returns the expected:
Expected: b2b_registration_request -> b2bRegistrationRequest
Received: b2b_registration_request -> b2BRegistrationRequest

Assumptions:
  - If a letter proceeded by a number is followed by an underscore or dash, the letter should not be upper cased

## index.js
  - Reordered the replace functions to be able to check for separators
  - Added ternary function to check if the character after the replace value is a underscore or dash and only changing case if it is not
## test.js
  - Added 4 tests for the example string

Fixes #77

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -49,8 +49,8 @@ const postProcess = (input, toUpperCase) => {
 	SEPARATORS_AND_IDENTIFIER.lastIndex = 0;
 	NUMBERS_AND_IDENTIFIER.lastIndex = 0;
 
-	return input.replace(SEPARATORS_AND_IDENTIFIER, (_, identifier) => toUpperCase(identifier))
-		.replace(NUMBERS_AND_IDENTIFIER, m => toUpperCase(m));
+	return input.replace(NUMBERS_AND_IDENTIFIER, (m, n, i) => ['_', '-'].includes(input.charAt(i + m.length)) ? m : toUpperCase(m))
```
Comment (sindresorhus) [inline index.js:52]: Don't use one character variable names.

Comment (JCrandall101) [reply index.js]: Got it, updated variables
